### ISSUE TITLE
Crash if osm_type property is missing

### ISSUE THREAD

**Issue by mspnr** [jld3103/osm-nominatim#5]
Example URL (query "11375"):
https://nominatim.openstreetmaps.org/search.php?q=11375&format=jsonv2

Nominatim output:
![1](https://user-images.githubusercontent.com/38891920/136708553-09fbb5b5-6cc8-4bdb-a40f-e1a51dca8e3e.png)

Stack:
```
E/flutter ( 4379): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter ( 4379): #0      new Place.fromJson (package:osm_nominatim/osm_nominatim.dart:270:35)
E/flutter ( 4379): #1      Nominatim.searchByName.<anonymous closure> (package:osm_nominatim/osm_nominatim.dart:122:34)
E/flutter ( 4379): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter ( 4379): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 4379): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 4379): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 4379): #6      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 4379): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 4379): #8      Nominatim.searchByName (package:osm_nominatim/osm_nominatim.dart:123:10)
```

Error cause:
![2](https://user-images.githubusercontent.com/38891920/136708621-4d15ecd4-4323-40e6-ae4f-eb9cad42ba61.png)

[Source code line](https://github.com/jld3103/osm-nominatim/blob/e17d40b3bf65ef79b92f0c19d7eaa0066a5dfaf4/lib/osm_nominatim.dart#L272)

Maybe some default value can be set it the property is missing?

**Comment by mspnr** [comment]
Probable relevant issue https://github.com/osm-search/Nominatim/issues/1521
